### ISSUE TITLE
fatal error: accumulatorcheckpoints.json.h: No such file or directory

### ISSUE THREAD

**Issue by crackfoo** [Primestonecoin/PrimeStone#1]
accumulatorcheckpoints.cpp:7:41: fatal error: accumulatorcheckpoints.json.h: No such file or directory
compilation terminated.
Makefile:3798: recipe for target 'libbitcoin_common_a-accumulatorcheckpoints.o' failed
make[2]: *** [libbitcoin_common_a-accumulatorcheckpoints.o] Error 1
make[2]: Leaving directory '/usr/local/src/PrimeStone/src'
Makefile:7858: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/PrimeStone/src'
Makefile:681: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by KrzysztofPrimeStone** [comment]
Resolved

**Comment by BAKFR** [comment]
I encountered this error several times in different cryptocurrencies. May I know how you resolved it ?

**Comment by KrzysztofPrimeStone** [comment]
We added this file to our repo.

**Comment by BAKFR** [comment]
Thank for your response.

DId you create the file your self, or does it came from PIVX ? There seem to be a lot of blockchain-specific data inside it.
